---
- hosts: localhost
  remote_user: root
  connection: local
  gather_facts: false
  tasks:
    - name: Install subscription-manager
      shell: yum install subscription-manager.x86_64 -y

    - name: Change SELINUX
      shell: sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config

    - name: Stop Firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Install Epel-release
      ansible.builtin.yum:
        name: epel-release
        state: latest

    - name: Update RHEL Family OS packages
      yum:
        name: '*'
        state: latest

    - name: Install package
      ansible.builtin.yum:
        name: [httpd, mariadb-server, mlocate, vim, net-tools, wget, curl, php, php-cli, php-common, php-fpm, php-gd, php-intl, php-json, php-mbstring, php-mysqlnd, php-opcache, php-pdo, php-xml, php-xmlrpc, php-pecl-zip, php-soap]

    - name: Git Checkout
      ansible.builtin.git:
        repo: https://github.com/moodle/moodle.git
        dest: /var/www/moodle
